name: CI Linux
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Unset Android SDK
        run: echo "ANDROID_HOME=" >> $GITHUB_ENV

      - name: Install Bazelisk
        run: |
          sudo curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.28.1/bazelisk-linux-amd64"
          chmod +x bazelisk-linux-amd64

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Bazel Remote Cache
        run: |
          cat >> .bazelrc <<'EOF'
          build --remote_cache=https://storage.googleapis.com/argus-cache
          build --google_default_credentials
          EOF

      - name: Build
        run: ./bazelisk-linux-amd64 build //...
