name: CI MacOS
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Unset Android SDK
        run: echo "ANDROID_HOME=" >> $GITHUB_ENV
        
      - name: Install Bazelisk
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.28.1/bazelisk-darwin-arm64
          chmod +x bazelisk-darwin-arm64
          mv bazelisk-darwin-arm64 bazel

      - name: Configure Bazel Remote Cache
        env:
          GCP_CREDENTIALS: ${{ secrets.GCS_BUCKET }}
          ARGUS_CACHE: ${{ secrets.ARGUS_CACHE }}
        run: |
          echo "${GCP_CREDENTIALS}" > /tmp/gcp-creds.json
          echo "build --remote_cache=${ARGUS_CACHE}" >> .bazelrc
          echo "build --remote_upload_local_results=true" >> .bazelrc
          echo "build --google_credentials=/tmp/gcp-creds.json" >> .bazelrc
          
      - name: Build
        run: ./bazel build //...

      - name: Cleanup credentials
        if: always()
        run: rm -f /tmp/gcp-creds.json
